sudo: required
services:
  - docker

before_install:
  - docker build -t dragonslayer142/docker-react -f DockerfileDev .

script:
  - docker run dragonslayer142/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: docker-react
  env: "Docker-env"
  bucket_name: "some-bucket-name"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY

