version: '3'

services:
  react-app:
    build:
      context: .
      dockerfile: DockerfileDev
    ports:
      - "3000:3000"
    volumes:
      - /usr/app/node_modules
      - ./:/usr/app
  tests:
    build:
      context: .
      dockerfile: DockerfileDev
    volumes:
      - /usr/app/node_modules
      - ./:/usr/app
    command: ["npm", "run", "test"]
